# Generated by Django 4.0.6 on 2022-08-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_awesome_api', '0004_post_content_post_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
